#ifndef KAITO_CRC16_FOLDING_H
#define KAITO_CRC16_FOLDING_H

// Original CRC-16/ARC derivation: Documentation/design.md (2026-09-09).
// Instruction semantics only: Arm ACLE Neon Intrinsics Reference, Intel SDM
// Vol. 2 PCLMULQDQ; runtime feature query: Apple architectural differences doc.
// This header uses the existing C bridge so no new binary target is required.
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <sys/sysctl.h>

static inline int kk_crc16_has_folding(void) {
#if defined(__aarch64__)
    int supported = 0;
    size_t size = sizeof(supported);
    return sysctlbyname("hw.optional.arm.FEAT_PMULL", &supported, &size, NULL, 0) == 0
        && size == sizeof(supported) && supported == 1;
#elif defined(__x86_64__)
    // CPUID leaf 1 ECX bit 1. No AVX or OSXSAVE requirement for legacy XMM CLMUL.
    unsigned int a = 1, b, c, d;
    __asm__("cpuid" : "+a"(a), "=b"(b), "=c"(c), "=d"(d));
    return (c & 2) != 0;
#else
    return 0;
#endif
}

#if defined(__aarch64__)
#include <arm_neon.h>
#define KK_CRC_TARGET __attribute__((target("aes")))
typedef uint64x2_t kk_crc_vec;
static inline kk_crc_vec kk_crc_pair(uint64_t lo, uint64_t hi) {
    return (uint64x2_t){lo, hi};
}
static inline kk_crc_vec kk_crc_xor(kk_crc_vec a, kk_crc_vec b) { return veorq_u64(a, b); }
static inline KK_CRC_TARGET kk_crc_vec kk_crc_fold(kk_crc_vec a, kk_crc_vec k) {
    return veorq_u64((uint64x2_t)vmull_p64(a[0], k[0]),
                    (uint64x2_t)vmull_high_p64((poly64x2_t)a, (poly64x2_t)k));
}
#elif defined(__x86_64__)
#include <emmintrin.h>
#include <wmmintrin.h>
#define KK_CRC_TARGET __attribute__((target("pclmul")))
typedef __m128i kk_crc_vec;
static inline kk_crc_vec kk_crc_pair(uint64_t lo, uint64_t hi) {
    return _mm_set_epi64x((long long)hi, (long long)lo);
}
static inline kk_crc_vec kk_crc_xor(kk_crc_vec a, kk_crc_vec b) { return _mm_xor_si128(a, b); }
static inline KK_CRC_TARGET kk_crc_vec kk_crc_fold(kk_crc_vec a, kk_crc_vec k) {
    return _mm_xor_si128(_mm_clmulepi64_si128(a, k, 0x00),
                         _mm_clmulepi64_si128(a, k, 0x11));
}
#endif

#if defined(__aarch64__) || defined(__x86_64__)
static inline kk_crc_vec kk_crc_load(const uint8_t *p) {
    kk_crc_vec v;
    memcpy(&v, p, 16); // Unaligned, alias-safe, exactly 16 bytes.
    return v;
}

// Precondition: instruction support checked, count >= 64 and divisible by 16,
// bytes spans count readable bytes, table spans the existing 8 * 256 entries.
// No heap allocation; every vector load follows a complete-block count check.
static __inline__ KK_CRC_TARGET __attribute__((noinline))
uint16_t kk_crc16_fold_blocks(const uint8_t *bytes, size_t count,
                              uint16_t crc, const uint16_t *table) {
    // In GF(2)[x]/(0x14003), x^-1 = 0xA001. For distance d bits, multiply
    // low/high 64-bit halves by x^-d / x^(64-d), respectively. Constants
    // are generated by d applications of the original reflected bit step.
    const kk_crc_vec k512 = kk_crc_pair(0xf0c1, 0xbffa);
    const kk_crc_vec k128 = kk_crc_pair(0x90c1, 0xccc1);
    kk_crc_vec a = kk_crc_xor(kk_crc_load(bytes), kk_crc_pair(crc, 0));
    kk_crc_vec b = kk_crc_load(bytes + 16);
    kk_crc_vec c = kk_crc_load(bytes + 32);
    kk_crc_vec d = kk_crc_load(bytes + 48);
    bytes += 64;
    count -= 64;
    while (count >= 64) {
        a = kk_crc_xor(kk_crc_fold(a, k512), kk_crc_load(bytes));
        b = kk_crc_xor(kk_crc_fold(b, k512), kk_crc_load(bytes + 16));
        c = kk_crc_xor(kk_crc_fold(c, k512), kk_crc_load(bytes + 32));
        d = kk_crc_xor(kk_crc_fold(d, k512), kk_crc_load(bytes + 48));
        bytes += 64;
        count -= 64;
    }
    a = kk_crc_xor(kk_crc_fold(a, k128), b);
    a = kk_crc_xor(kk_crc_fold(a, k128), c);
    a = kk_crc_xor(kk_crc_fold(a, k128), d);
    while (count >= 16) {
        a = kk_crc_xor(kk_crc_fold(a, k128), kk_crc_load(bytes));
        bytes += 16;
        count -= 16;
    }
    // The last representative needs x^-128 and reduction to 16 bits. Reuse
    // the existing slicing tables on its exact 16-byte stack representation.
    uint64_t words[2];
    memcpy(words, &a, 16);
    crc = 0;
    for (unsigned i = 0; i < 2; ++i) {
        uint64_t w = words[i] ^ crc;
        crc = table[7*256 + (w & 255)] ^ table[6*256 + ((w >> 8) & 255)]
            ^ table[5*256 + ((w >> 16) & 255)] ^ table[4*256 + ((w >> 24) & 255)]
            ^ table[3*256 + ((w >> 32) & 255)] ^ table[2*256 + ((w >> 40) & 255)]
            ^ table[256 + ((w >> 48) & 255)] ^ table[w >> 56];
    }
    return crc;
}
#undef KK_CRC_TARGET
#else
static inline uint16_t kk_crc16_fold_blocks(const uint8_t *bytes, size_t count,
                                           uint16_t crc, const uint16_t *table) {
    return crc; // Unreachable: feature detection is false on other architectures.
}
#endif
#endif
